# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and test on ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Ubuntu
            os: ubuntu-latest
            swift-version: "6.0"
          - name: macOS
            os: macos-latest
            swift-version: ""
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - uses: swift-actions/setup-swift@v2
      if: matrix.swift-version != ''
      with:
        swift-version: ${{ matrix.swift-version }}
    - name: Show toolchain
      run: swift --version
    - name: Show Xcode version
      if: runner.os == 'macOS'
      run: xcodebuild -version
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
